# Generated by Django 2.2.6 on 2020-04-27 17:56

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='prof_pic',
            field=models.ImageField(upload_to='prof_pic/', validators=[user.models.validate_file_size], verbose_name=''),
        ),
    ]
